apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: icici
  name: icici
spec:
  ports:
  - name: 8081-8080
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: icici
  type: ClusterIP
status:
  loadBalancer: {}
